import pandas as pd

data = {
    "ID": [
        "Custom-4", "Custom-6","20mer-A", "20mer-B", "24mer", "25mer", "36mer", "48mer", "50mer",
         "Custom-60","Custom-64", "Custom-85", "Custom-100A",  "Custom-100B"
    ],
    "Length": [
        4, 6 ,20, 20, 24, 25, 36, 48, 50, 60, 64, 85, 100, 100,

    ],
    "HP Sequence": [
        "HHPH", "HPHPHH",
        "HPHPPHHPHPPHPHHPPHPH", "HHHPPHPHPHPPHPHPHPPH", "HHPPHPPHPPHPPHPPHPPHPPHH", "PPHPPHHPPPPHHPPPPHHPPPPHH",
        "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP", "PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH",
        "HHPHPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH",

       "PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP",
        "HHHHHHHHHHHHPHPHPPHHPPHHPPHPPHHPPHHPPHPPHHPPHHPPHPHPHHHHHHHHHHHH",
        "HHHHPPPPHHHHHHHHHHHHPPPPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHPPHHPPHHPPHPH",
        "PPPHHPPHHHHPPHHHPHHPHHPHHHHPPPPPPPPHHHHHHPPHHHHHHPPPPPPPPPHPHHPHHHHHHHHHHHPPHHHPHHPHPPHPHHHPPPPPPHHH",
        "PPPPPPHPHHPPPPPHHHPHHHHHPHHPPPPHHPPHHPHHHHHPHHHHHHHHHHPHHPHHHHHHHPPPPPPPPPPPHHHHHHHPPHPHHHPPPPPPHPHH",


    ],
    "Best Known Energy": [
        1, 2, 9, 10, 9, 8, 14, 23, 21, 36,
        42, 53, 50, 48,

    ]
}
df = pd.DataFrame(data)
pkl_file_path = "data/hp_sequences_dataset.pkl"
df.to_pickle(pkl_file_path)